### ISSUE TITLE
Leverage index on queries

### ISSUE THREAD

**Issue by thorfour** [polarsignals/arcticdb#7]
Right now when we query we iterate over the entire index. 

This makes a query an O(N) operation, and renders the index pointless. We should instead leverage the sorted nature during queries to minimize the number of granules we have to look at. 

Ideally we'd also do this on insert as well.

**Comment by brancz** [comment]
I kind of have the feeling that we need to implement our own ordered list in order for us to perform the type of queries we want on it. Before we do that though, we should have a closer look at the google btree capabilities again.
