### ISSUE TITLE
Duplicate ParquetNodeToType()

### ISSUE THREAD

**Issue by ohkinozomu** [polarsignals/arcticdb#75]
https://github.com/polarsignals/arcticdb/blob/450025ff363cb7241d9a038dcaf74b8f2779f2ac/pqarrow/arrow.go#L379
https://github.com/polarsignals/arcticdb/blob/0c97de2410a804308b52574cdb1d5073d436ae64/query/logicalplan/expr.go#L127

There are two `ParquetNodeToType` functions in `pqarrow` and `logicalplan` with the same name and the same functionality, so it would make sense to make one function to be used around.

However, there are perhaps two problems with it.

1. From its functionality,  `pqarrow` package would be the appropriate place ( it means `parquet-arrow`, doesn't it? ), but it imports `logicalplan`, which causes an import cycle.

2. To avoid using panic(), we need to change to `DataType(*dynparquet.Schema) (arrow.DataType, error)` in the expr interface.
https://github.com/polarsignals/arcticdb/blob/1bd737630d2c68487961bd7d52c50503924e5ad9/query/logicalplan/builder.go#L82

Any thoughts?

**Comment by brancz** [comment]
> From its functionality, pqarrow package would be the appropriate place ( it means parquet-arrow, doesn't it? ), but it imports logicalplan, which causes an import cycle.

Yes, that's exactly why we initially duplicated it.

> To avoid using panic(), we need to change to DataType(*dynparquet.Schema) (arrow.DataType, error) in the expr interface.

Perfectly happy with that. The panic was actually a left over from prototyping when we wanted to fail hard in cases that we didn't fully implement through.

Maybe we can just extract it into another package to break the cyclic import? Maybe a `convert` sub-package under `pqarrow`?
