### ISSUE TITLE
Possible problem inside function `splitGranule`

### ISSUE THREAD

**Issue by ostafen** [polarsignals/arcticdb#81]
Hi, all, I noticed that if I increase the number of concurrent writers inside function `Test_Table_Concurrency()`, I get the following error:
```bash
"failed to delete granule during split"
```

Thinking about it, this could be due to the following. After we reach the following statement
```golang
// set the newGranules pointer, so new writes will propogate into these new granules	
granule.newGranules = granules
```
inside `splitGranule()`, we propagate new inserts also to child granules. Then, under an high concurrent pressure, compaction could be triggered also for some of the several child granules, even before they were inserted in the index.
So, when the control recheases this line (in the context of the child granule)
```golang
deleted := index.Delete(granule)
if deleted == nil {
	level.Error(t.logger).Log("msg", "failed to delete granule during split")
}
```
we will not find it inside the index. If we simply ignore the error log, we could end with a situation, where some granules are not deleted properly from the index. I think that a possible solution to this could the disabling compaction for newly created granules until we are sure we inserted them inside the index. So, something like:

```golang

// we disable compaction for new granules before allowing new insert to be propagated to them
for _, childGranule := range granules {
        childGranule.metadata.pruned.Store(1)
}

// we restore the possibility to trigger compaction after we exited the function
defer func() {
      for _, childGranule := range granules {
	      childGranule.metadata.pruned.Store(0)
      }
}()

// set the newGranules pointer, so new writes will propogate into these new granules
granule.newGranules = granules

...
```

If this makes sense for you, I will submit a PR with the fix

**Comment by brancz** [comment]
Very nice find! Could this be a fix/explanation for #71?

At first sight, this looks plausible to me, but @thorfour has spent much more time with this code than me, so I think it would be good for him to take a closer look as well.

**Comment by ostafen** [comment]
This could be (at least potentially) related to #71, but in this case, when a granule is not found in the index, we get an error message logged in the console. It seems however that in #71, you simply get a test failure

**Comment by thorfour** [comment]
Thank you for the issue and the quick fix!
